ifdef::backend-html5[]
image::img/logo.svg[Logo,100,100,float="right",align="right"]
endif::[]

== Jane Smith

[%hardbreaks]
555-555-5555
jane.smith@email.com

I have a passion for making resumes.

=== Skill Summary

[%hardbreaks]
Writing resumes.
Proficient with various markup formats.
Converting structured plain text documents into PDF.

.Tool Proficiency
--
Markdown, HTML, CSS, pandoc, Neovim, tmux, GNU Make, wkhtmltopdf
--

=== Professional Experience

==== Fantasy Resumes, Inc.

_October 2016 - Present_

.Resume Fairy
--
Provide resumes that clients dream up under their pillows while they sleep.
This involves deciphering each client's dream with specialized tools and
producing it for the client before she or he wakes.  To accomplish this a
template is used to convert structured plain text into a nice looking resume.
--

==== Curriculum Vitae, LLC

_July 2004 - October 2016_

.Word Smith | April 2010 – October 2016
--
Hammered out words to produce curriculum vitae for clients.  Corrected errors
detected by the typo snipers.

Developed a resume template the separated layout and content so word smiths can
focus on the important things: hammering out words.
--

.Typo Sniper | July 2004 – April 2010
--
Analyzed the quality of curriculum vitae produced by the word smiths.
Documents that contained errors and typos were sent back for corrections.

Improved efficiency by providing error correction tools early in the process,
such as spell check.
--

=== Education

*Resume University* | _2000 – 2004_ | Bachelor's degree in resume writing

*Plain Text High School* | _2000_ | Graduated
